'use strict';
/* js/data.js — statik veri: isim havuzları, kıtalar, ülkeler, ligler, takımlar, kupalar */
/* ================= NAME POOLS ================= */
const NATS={
tr:{c:'TUR',f:['Emre','Burak','Kerem','Arda','Mert','Yusuf','Kaan','Berat','Umut','Onur','Cenk','Halil','Ozan','Tolga','Serkan','Volkan','Barış','Efe','Doruk','Çağlar','İsmail','Salih','Furkan','Enes','Oğuz','Hakan','Semih','Taha','Alper','Metin','Deniz','Görkem','Batuhan','Yiğit','Emirhan','Ferdi'],
 l:['Yılmaz','Kaya','Demir','Şahin','Çelik','Aydın','Arslan','Doğan','Kılıç','Koç','Kurt','Özkan','Şimşek','Polat','Erdoğan','Aksoy','Güler','Bulut','Duman','Tekin','Yıldırım','Karaca','Öztürk','Ateş','Toprak','Bozkurt','Sönmez','Turan','Avcı','Keskin','Sarı','Uçar','Baran','Acar','Tuna','Korkmaz']},
en:{c:'ENG',f:['Jack','Harry','Oliver','George','Charlie','Jacob','Thomas','Oscar','William','James','Henry','Leo','Joshua','Freddie','Archie','Logan','Alex','Mason','Callum','Kyle','Reece','Jayden','Ethan','Lewis','Connor','Ben','Sam','Dan'],
 l:['Smith','Jones','Taylor','Brown','Wilson','Davies','Evans','Walker','Wright','Robinson','Thompson','White','Hughes','Edwards','Green','Hall','Wood','Harris','Clarke','Baker','Ward','Turner','Carter','Shaw','Palmer','Mills','Barnes','Gray']},
es:{c:'ESP',f:['Sergio','Carlos','Pablo','Álvaro','Diego','Javier','Iker','Mikel','Ander','Unai','Dani','Adrián','Hugo','Nacho','Raúl','Pedro','Iago','César','Rubén','Marcos','Víctor','Alejandro','Jorge','Aitor','Borja','Isco','Rodri','Gerard'],
 l:['García','Fernández','López','Martínez','Sánchez','Pérez','Gómez','Díaz','Torres','Ramos','Navarro','Moreno','Alonso','Gutiérrez','Vázquez','Molina','Ortiz','Castro','Rubio','Iglesias','Serrano','Herrera','Cano','Vidal','Campos','Rey','Soler','Costa']},
de:{c:'GER',f:['Lukas','Leon','Finn','Jonas','Niklas','Tim','Felix','Maximilian','Jan','Nico','Florian','Marcel','Kevin','Timo','Julian','Pascal','Tobias','Moritz','Emil','Lennart','Fabian','David','Simon','Erik','Jannik','Marius','Paul','Til'],
 l:['Müller','Schmidt','Schneider','Fischer','Weber','Wagner','Becker','Hoffmann','Schulz','Koch','Richter','Klein','Wolf','Neumann','Schwarz','Zimmermann','Braun','Krüger','Hofmann','Lange','Werner','Krause','Meier','Lehmann','Vogel','Frank','Berger','Roth'],},
it:{c:'ITA',f:['Marco','Alessandro','Lorenzo','Matteo','Federico','Davide','Andrea','Simone','Luca','Gabriele','Riccardo','Tommaso','Nicolò','Antonio','Giovanni','Francesco','Pietro','Salvatore','Emanuele','Cristian','Alessio','Domenico','Giacomo','Filippo','Mattia','Stefano','Enrico','Dario'],
 l:['Rossi','Russo','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco','Bruno','Gallo','Conti','De Luca','Costa','Giordano','Mancini','Rizzo','Lombardi','Moretti','Barbieri','Fontana','Santoro','Caruso','Ferri','Villa','Serra','Longo']},
fr:{c:'FRA',f:['Antoine','Hugo','Lucas','Théo','Adrien','Jules','Léo','Mathis','Nathan','Enzo','Clément','Maxime','Alexandre','Romain','Florian','Bastien','Corentin','Quentin','Yanis','Amine','Karim','Rayan','Moussa','Ibrahim','Sofiane','Mehdi','Axel','Loïc'],
 l:['Martin','Bernard','Dubois','Moreau','Laurent','Simon','Michel','Lefebvre','Leroy','Roux','Fournier','Girard','Bonnet','Dupont','Lambert','Rousseau','Vincent','Faure','André','Mercier','Blanc','Guérin','Chevalier','Perrin','Diallo','Traoré','Ndiaye','Keita']},
br:{c:'BRA',f:['Gabriel','Lucas','Matheus','Pedro','Vinícius','Rafael','Bruno','Thiago','João','Felipe','Gustavo','Rodrigo','Caio','Renan','Igor','Diego','Eduardo','Wesley','Éverton','Douglas','Anderson','Leandro','Márcio','Paulo','Alex','Denílson','Wallace','Maurício'],
 l:['Silva','Santos','Oliveira','Souza','Costa','Pereira','Almeida','Ferreira','Rodrigues','Gomes','Martins','Araújo','Ribeiro','Carvalho','Lima','Barbosa','Rocha','Dias','Moura','Cardoso','Teixeira','Correia','Cavalcanti','Freitas','Ramos','Farias','Pinto','Moraes']},
ar:{c:'ARG',f:['Julián','Lautaro','Nicolás','Emiliano','Rodrigo','Gonzalo','Ezequiel','Matías','Franco','Facundo','Agustín','Santiago','Joaquín','Ignacio','Tomás','Lucas','Federico','Maximiliano','Bruno','Thiago','Valentín','Ramiro','Lisandro','Marcos','Ángel','Cristian','Diego','Gastón'],
 l:['González','Rodríguez','Fernández','López','Martínez','Álvarez','Romero','Suárez','Benítez','Acosta','Medina','Herrera','Aguirre','Giménez','Molina','Castro','Rojas','Ortiz','Núñez','Cabrera','Vega','Sosa','Ledesma','Villalba','Paredes','Correa','Ponce','Ríos']},
nl:{c:'NED',f:['Daan','Sem','Luuk','Jesse','Thijs','Lars','Levi','Ruben','Bram','Timo','Joost','Sven','Niels','Stijn','Wout','Teun','Jurriën','Mees','Gijs','Koen','Bas','Rick','Tygo','Julian'],
 l:['de Jong','de Vries','van den Berg','Bakker','Janssen','Visser','Smit','Meijer','Mulder','Bos','Vos','Peters','Hendriks','van Leeuwen','Dekker','Brouwer','Dijkstra','Smits','Kuipers','Veldman','Willems','Post','Kok','van Dam']},
ng:{c:'NGA',f:['Chukwu','Emeka','Ikenna','Obinna','Chinedu','Kelechi','Segun','Tunde','Femi','Ade','Samuel','Victor','Peter','Sunday','Godwin','Musa','Ibrahim','Aliyu','Uche','Efe','Osaze','Nonso'],
 l:['Okafor','Okoye','Eze','Nwachukwu','Obi','Adeyemi','Adebayo','Okonkwo','Balogun','Lawal','Abubakar','Ogunleye','Nwosu','Igwe','Onyeka','Udo','Anyanwu','Olawale','Ekong','Sani']},
sn:{c:'SEN',f:['Mamadou','Ousmane','Ibrahima','Cheikh','Moussa','Abdoulaye','Pape','Serigne','Modou','Alioune','Babacar','Amadou','Idrissa','Sekou','Lamine','Omar','Demba','Malick','Boubacar','Assane'],
 l:['Diallo','Ndiaye','Sow','Diop','Gueye','Cissé','Faye','Sarr','Ba','Kane','Sy','Seck','Mbaye','Niang','Diouf','Thiam','Camara','Badji','Konaté','Touré']},
gh:{c:'GHA',f:['Kwame','Kofi','Kwesi','Yaw','Kojo','Kwabena','Michael','Daniel','Joseph','Emmanuel','Isaac','Prince','Felix','Richard','Stephen','Eric','Bernard','Solomon','Gideon','Enoch'],
 l:['Mensah','Boateng','Owusu','Appiah','Asante','Osei','Agyemang','Annan','Tetteh','Quaye','Addo','Frimpong','Acheampong','Darko','Amoah','Ofori','Sarpong','Adjei','Opoku','Yeboah']},
cm:{c:'CMR',f:['Samuel','André','Vincent','Joël','Serge','Patrick','Alain','Christian','Éric','Franck','Georges','Thierry','Cédric','Yannick','Bertrand','Rodrigue','Landry','Arnaud','Blaise','Hervé'],
 l:['Abanda','Bekono','Elong','Manga','Ndip','Ngu','Oyongo','Tabi','Zoa','Ekani','Mbah','Nfor','Ashu','Tanyi','Ayuk','Enow','Fouda','Ondoa','Bilé','Essome']},
pt:{c:'POR',f:['João','Tiago','Diogo','Gonçalo','Rúben','André','Bruno','Nuno','Pedro','Ricardo','Miguel','Fábio','Hélder','Renato','Sérgio','Vasco','Duarte','Afonso','Henrique','Leandro'],
 l:['Silva','Santos','Ferreira','Pereira','Oliveira','Costa','Rodrigues','Martins','Sousa','Fernandes','Gonçalves','Gomes','Lopes','Marques','Alves','Almeida','Ribeiro','Pinto','Carvalho','Teixeira']},
us:{c:'USA',f:['Tyler','Brandon','Jordan','Austin','Caleb','Landon','Zack','Cody','Chase','Bryce','Devin','Trevor','Dylan','Hunter','Colton','Gavin','Brayden','Weston','Reed','Cole'],
 l:['Johnson','Miller','Davis','Garcia','Martinez','Anderson','Jackson','Moore','Lee','Perez','Thompson','Harris','Sanchez','Clark','Lewis','Walker','Young','Allen','King','Scott']},
mx:{c:'MEX',f:['Alejandro','Luis','José','Juan','Diego','Fernando','Ricardo','Eduardo','Roberto','Miguel','Andrés','Emilio','Raúl','Óscar','Uriel','Édgar','Rodolfo','Gerardo','Israel','Marco'],
 l:['Hernández','García','Martínez','López','González','Rodríguez','Sánchez','Ramírez','Cruz','Flores','Gómez','Vargas','Reyes','Jiménez','Torres','Aguilar','Mendoza','Rojas','Ortega','Castillo']},
sa:{c:'KSA',f:['Mohammed','Abdullah','Salem','Fahad','Khalid','Saud','Faisal','Nawaf','Turki','Sultan','Bandar','Majed','Yasser','Hassan','Omar','Ali','Ahmed','Saad','Rakan','Ziyad'],
 l:['Al-Qahtani','Al-Ghamdi','Al-Otaibi','Al-Harbi','Al-Shehri','Al-Zahrani','Al-Dossari','Al-Mutairi','Al-Anazi','Al-Subaie','Al-Amri','Al-Malki','Al-Juhani','Al-Salem','Al-Rashid','Al-Bishi','Al-Asmari','Al-Yami','Al-Shamrani','Al-Hamdan']},
jp:{c:'JPN',f:['Takumi','Kaito','Yuto','Sota','Riku','Haruto','Daiki','Kenta','Shota','Ren','Yuma','Kosuke','Ryota','Tatsuya','Keisuke','Naoki','Hayato','Tsubasa','Itsuki','Sho'],
 l:['Sato','Suzuki','Takahashi','Tanaka','Watanabe','Ito','Yamamoto','Nakamura','Kobayashi','Kato','Yoshida','Yamada','Sasaki','Matsumoto','Inoue','Kimura','Hayashi','Shimizu','Mori','Abe']},
eg:{c:'EGY',f:['Ahmed','Mohamed','Mahmoud','Mostafa','Omar','Karim','Tarek','Hossam','Amr','Khaled','Youssef','Ramy','Sherif','Hany','Waleed','Islam','Sami','Adel','Fathi','Nabil'],
 l:['Hassan','Ibrahim','Abdelrahman','El-Sayed','Farouk','El-Masry','Ezzat','Shawky','Sobhi','Kamel','Fathy','Ghaly','Ashour','Zaki','Hamdy','Selim','Mansour','Awad','Taha','Ramadan']},
be:{c:'BEL',f:['Thomas','Kevin','Romelu','Dries','Axel','Youri','Leandro','Jeremy','Hans','Wout','Arthur','Lois','Senne','Matteo','Bryan','Elias','Nathan','Maxim'],
 l:['Vermeulen','Peeters','Maes','Jacobs','Willems','Claes','Goossens','Wouters','De Smet','Dubois','Lemaire','Vandenberghe','Verhoeven','Declercq','Van Damme','Mertens','Bogaert','Deprez']},
hr:{c:'CRO',f:['Luka','Ivan','Marko','Josip','Mateo','Ante','Domagoj','Nikola','Filip','Borna','Petar','Duje','Stipe','Lovro','Tin','Karlo','Fran','Roko'],
 l:['Horvat','Kovačević','Babić','Marić','Novak','Vuković','Jurić','Knežević','Radić','Šimić','Perić','Pavlović','Blažević','Tomić','Bašić','Grgić','Matić','Vidović']},
rs:{c:'SRB',f:['Nemanja','Aleksandar','Stefan','Dušan','Miloš','Filip','Luka','Uroš','Marko','Nikola','Lazar','Vuk','Andrija','Ognjen','Strahinja','Veljko','Petar','Bogdan'],
 l:['Jovanović','Petrović','Nikolić','Marković','Đorđević','Stojanović','Ilić','Pavlović','Ristić','Todorović','Milošević','Živković','Simić','Lukić','Mitrović','Kostić','Radovanović','Savić']},
pl:{c:'POL',f:['Robert','Piotr','Jakub','Kamil','Bartosz','Michał','Krzysztof','Arkadiusz','Sebastian','Mateusz','Przemysław','Grzegorz','Damian','Tomasz','Łukasz','Adam','Paweł','Wojciech'],
 l:['Nowak','Kowalski','Wiśniewski','Wójcik','Kowalczyk','Kamiński','Lewandowski','Zieliński','Szymański','Woźniak','Dąbrowski','Kozłowski','Jankowski','Mazur','Kwiatkowski','Krawczyk','Piotrowski','Grabowski']},
cz:{c:'CZE',f:['Tomáš','Patrik','Vladimír','Jakub','Ondřej','Adam','Lukáš','David','Petr','Martin','Jan','Michal','Filip','Václav','Antonín','Matěj','Daniel','Marek'],
 l:['Novák','Svoboda','Novotný','Dvořák','Černý','Procházka','Kučera','Veselý','Horák','Němec','Marek','Pospíšil','Pokorný','Hájek','Jelínek','Král','Beneš','Fiala']},
gr:{c:'GRE',f:['Giorgos','Dimitris','Kostas','Nikos','Christos','Vasilis','Petros','Panagiotis','Anastasios','Stefanos','Manolis','Thanasis','Lefteris','Alexandros','Ilias','Sokratis','Odysseas','Yannis'],
 l:['Papadopoulos','Georgiou','Nikolaou','Ioannidis','Vlachos','Karagiannis','Antoniou','Makris','Pappas','Samaras','Fotiadis','Stavrou','Christou','Dimitriou','Athanasiou','Petridis','Manolas','Lambropoulos']},
no:{c:'NOR',f:['Erling','Martin','Sander','Kristian','Jonas','Fredrik','Emil','Håkon','Ola','Sondre','Mats','Even','Aron','Tobias','Vegard','Marius','Andreas','Henrik'],
 l:['Hansen','Johansen','Olsen','Larsen','Andersen','Nilsen','Pedersen','Kristiansen','Jensen','Karlsen','Berg','Haugen','Solberg','Moen','Lund','Dahl','Strand','Nygård']},
se:{c:'SWE',f:['Emil','Viktor','Alexander','Gustav','Oscar','Anton','Elias','Isak','Ludvig','Hugo','Filip','Jesper','Rasmus','Måns','Albin','Melker','Noel','Kalle'],
 l:['Andersson','Johansson','Karlsson','Nilsson','Eriksson','Larsson','Olsson','Persson','Svensson','Gustafsson','Pettersson','Jonsson','Jansson','Hansson','Bergström','Lindberg','Sandberg','Forsberg']},
dk:{c:'DEN',f:['Christian','Mikkel','Rasmus','Jonas','Andreas','Kasper','Frederik','Magnus','Emil','Oliver','Victor','Simon','Nikolaj','Anders','Jesper','Lasse','Mads','Tobias'],
 l:['Jensen','Nielsen','Hansen','Pedersen','Andersen','Christensen','Larsen','Sørensen','Rasmussen','Jørgensen','Petersen','Madsen','Kristensen','Olsen','Thomsen','Christiansen','Poulsen','Johansen']},
ch:{c:'SUI',f:['Granit','Remo','Fabian','Silvan','Noah','Ruben','Michel','Yann','Loris','Andi','Cedric','Steven','Nico','Ulisses','Simon','Dan','Vincent','Joel'],
 l:['Müller','Meier','Schmid','Keller','Weber','Huber','Schneider','Steiner','Brunner','Baumann','Frei','Widmer','Zuber','Kobel','Rieder','Amdouni','Vargas','Sierro']},
at:{c:'AUT',f:['David','Marcel','Konrad','Stefan','Christoph','Xaver','Nicolas','Patrick','Florian','Michael','Maximilian','Alexander','Sasa','Andreas','Philipp','Thomas','Lukas','Julian'],
 l:['Gruber','Huber','Bauer','Wagner','Pichler','Steiner','Moser','Mayer','Hofer','Leitner','Berger','Fuchs','Eder','Fischer','Schmid','Winkler','Weber','Aigner']},
ua:{c:'UKR',f:['Andriy','Oleksandr','Mykhailo','Ruslan','Vitaliy','Serhiy','Roman','Taras','Yaroslav','Bohdan','Denys','Illia','Artem','Volodymyr','Maksym','Vadym','Yevhen','Oleh'],
 l:['Shevchenko','Kovalenko','Bondarenko','Tkachenko','Kravchenko','Boyko','Melnyk','Marchenko','Lysenko','Rudenko','Sydorenko','Zinchenko','Yaremchuk','Malinovskyi','Dovbyk','Mudryk','Stepanenko','Petrenko']},
ro:{c:'ROU',f:['Andrei','Ionut','Razvan','Nicolae','Alexandru','Vlad','Denis','Florin','Bogdan','Cristian','Gabriel','Mihai','Stefan','Valentin','Daniel','Radu','Marius','Sergiu'],
 l:['Popescu','Ionescu','Popa','Radu','Dumitru','Stan','Stoica','Gheorghe','Matei','Constantin','Marin','Diaconu','Barbu','Nistor','Olaru','Man','Mitrita','Puscas']},
sct:{c:'SCO',f:['Andrew','Callum','Scott','Ryan','John','Kieran','Stuart','Grant','Billy','Lyndon','Che','Nathan','Aaron','Lewis','Angus','Struan','Ross','Kenny'],
 l:['Robertson','McGregor','Fraser','Christie','McTominay','Tierney','Armstrong','Hanley','Gilmour','Dykes','Adams','Patterson','Hickey','Ferguson','Doig','Souttar','McLean','Cooper']},
ie:{c:'IRL',f:['Séamus','Shane','Robbie','Jason','Callum','Adam','Josh','Chiedozie','Jayson','Nathan','Evan','Dara','Finn','Mikey','Jake','Ryan','Will','Sammie'],
 l:['Murphy','Kelly','OSullivan','Walsh','Smith','OBrien','Byrne','Ryan','OConnor','ONeill','Reilly','Doyle','McCarthy','Gallagher','Duffy','Lynch','Molumby','Ogbene']},
ru:{c:'RUS',f:['Aleksandr','Dmitri','Sergei','Andrei','Fyodor','Anton','Aleksei','Maksim','Ivan','Nikolai','Roman','Yuri','Artem','Igor','Denis','Vladimir','Pavel','Kirill'],
 l:['Ivanov','Smirnov','Kuznetsov','Popov','Sokolov','Lebedev','Kozlov','Novikov','Morozov','Petrov','Volkov','Solovyov','Vasilyev','Zaitsev','Pavlov','Semenov','Golovin','Miranchuk']},
co:{c:'COL',f:['Juan','Luis','James','Radamel','Davinson','Wilmar','Yerry','Duván','Rafael','Jefferson','Mateus','Johan','Daniel','Kevin','Jhon','Santiago','Andrés','Camilo'],
 l:['Rodríguez','Gómez','Muñoz','Cuadrado','Mina','Zapata','Borré','Sánchez','Arias','Lerma','Ospina','Uribe','Cardona','Barrios','Díaz','Quintero','Moreno','Cuesta']},
uy:{c:'URU',f:['Luis','Diego','Federico','Rodrigo','Matías','Nicolás','Sebastián','Giorgian','Facundo','Agustín','Manuel','Brian','Maximiliano','Santiago','Emiliano','Damián','Nahitan','Joaquín'],
 l:['Suárez','Godín','Valverde','Bentancur','Cavani','Torreira','Coates','Araújo','Olivera','Cáceres','Rossi','Vecino','Pereiro','Núñez','Ugarte','Viña','Varela','Sosa']},
cl:{c:'CHI',f:['Alexis','Arturo','Claudio','Gary','Charles','Eduardo','Mauricio','Diego','Ben','Erick','Marcelino','Guillermo','Gabriel','Víctor','Paulo','Felipe','Alexander','Iván'],
 l:['Sánchez','Vidal','Bravo','Medel','Aránguiz','Vargas','Isla','Valdés','Brereton','Pulgar','Núñez','Maripán','Suazo','Dávila','Galdames','Meneses','Osorio','Zaldivia']},
pe:{c:'PER',f:['Paolo','Jefferson','Christian','Renato','Yoshimar','Luis','André','Edison','Miguel','Sergio','Gianluca','Alex','Bryan','Marcos','Wilder','Andy','Piero','Raúl'],
 l:['Guerrero','Farfán','Cueva','Tapia','Yotún','Advíncula','Carrillo','Flores','Trauco','Peña','Lapadula','Valera','Reyna','López','Cartagena','Polo','Quispe','Ruidíaz']},
ec:{c:'ECU',f:['Enner','Moisés','Pervis','Piero','Gonzalo','Ángel','Jeremy','Kendry','Alan','Félix','Hernán','Jhegson','Robert','Byron','Diego','Willian','Michael','Joel'],
 l:['Valencia','Caicedo','Estupiñán','Hincapié','Plata','Mena','Sarmiento','Preciado','Torres','Palacios','Franco','Méndez','Arboleda','Castillo','Ordóñez','Pacho','Quiñónez','Angulo']},
py:{c:'PAR',f:['Miguel','Óscar','Gustavo','Ángel','Julio','Alejandro','Robert','Braian','Mathías','Andrés','Ramón','Junior','Antonio','Richard','Fabián','Diego','Iván','Blas'],
 l:['Almirón','Romero','Gómez','Cardozo','Enciso','Sanabria','Ortiz','Villasanti','Balbuena','Alderete','Bareiro','Rojas','Samudio','Espínola','Franco','Giménez','Cáceres','Riveros']},
ve:{c:'VEN',f:['Salomón','Josef','Yeferson','Tomás','Darwin','Jhon','Yangel','Jefferson','Rómulo','Wuilker','Nahuel','Cristian','Jon','Eduard','José','Alexander','Ronald','Yordan'],
 l:['Rondón','Martínez','Soteldo','Rincón','Machís','Murillo','Herrera','Savarino','Otero','Faríñez','Ferraresi','Casseres','Aramburu','Bello','Osorio','González','Hernández','Osorio']},
ci:{c:'CIV',f:['Didier','Yaya','Sébastien','Serge','Franck','Nicolas','Wilfried','Eric','Ibrahim','Jean','Odilon','Evan','Amad','Simon','Ousmane','Christian','Seko','Ghislain'],
 l:['Drogba','Touré','Haller','Aurier','Kessié','Pépé','Zaha','Bailly','Sangaré','Boly','Kossounou','Ndicka','Diallo','Adingra','Fofana','Kouamé','Gradel','Konan']},
dz:{c:'ALG',f:['Riyad','Islam','Sofiane','Youcef','Ramy','Aïssa','Adam','Amine','Ismaël','Rachid','Baghdad','Hicham','Farid','Zinedine','Yassine','Nabil','Karim','Mohamed'],
 l:['Mahrez','Slimani','Feghouli','Atal','Bensebaini','Mandi','Zerrouki','Gouiri','Bennacer','Chaïbi','Bounedjah','Boudaoui','Belaïli','Amoura','Benrahma','Ounas','Tahrat','Zorgane']},
tn:{c:'TUN',f:['Wahbi','Youssef','Aïssa','Hannibal','Ellyes','Mohamed','Seifeddine','Anis','Naïm','Ali','Ferjani','Dylan','Elias','Montassar','Wajdi','Bilel','Yassine','Hamza'],
 l:['Khazri','Msakni','Laïdouni','Mejbri','Skhiri','Dräger','Jaziri','Slimane','Sliti','Maâloul','Sassi','Bronn','Achouri','Talbi','Kechrida','Ifa','Meriah','Rafia']},
ml:{c:'MLI',f:['Amadou','Yves','Diadié','Moussa','Sékou','Hamari','Cheick','Adama','Boubacar','Falaye','Lassine','Mohamed','Kamory','Nene','Ibrahim','Sikou','Aliou','Mamadou'],
 l:['Haidara','Bissouma','Samassékou','Doumbia','Koita','Traoré','Diarra','Sacko','Fofana','Sissoko','Coulibaly','Camara','Dembélé','Kanté','Konaté','Keita','Niakaté','Djenepo']},
cd:{c:'COD',f:['Cédric','Chancel','Yoane','Théo','Gaël','Dieumerci','Arthur','Samuel','Silas','Meschack','Fiston','Grady','Ngonda','Joris','Yannick','Britt','Aaron','Noah'],
 l:['Bakambu','Mbemba','Wissa','Bongonda','Kakuta','Mbokani','Masuaku','Moutoussamy','Katompa','Elia','Mayele','Diemerci','Muleka','Kayembe','Bolingi','Nzuzi','Mpasi','Kalulu']},
kr:{c:'KOR',f:['Heung-min','Min-jae','Kang-in','Woo-young','Jae-sung','Ui-jo','Sang-ho','Young-gwon','In-beom','Chan-hee','Seung-ho','Tae-hwan','Moon-hwan','Jin-su','Gue-sung','Hyun-woo','Jun-ho','Seung-gyu'],
 l:['Son','Kim','Lee','Hwang','Jung','Park','Cho','Kwon','Hong','Baek','Oh','Yoon','Seol','Nam','Ahn','Ko','Ryu','Song']},
ir:{c:'IRN',f:['Sardar','Mehdi','Alireza','Karim','Saman','Ramin','Ahmad','Milad','Omid','Saeid','Vahid','Shoja','Morteza','Hossein','Ali','Amir','Reza','Kaveh'],
 l:['Azmoun','Taremi','Jahanbakhsh','Ansarifard','Ghoddos','Rezaeian','Noorollahi','Mohammadi','Ebrahimi','Ezatolahi','Amiri','Khalilzadeh','Pouraliganji','Kanaani','Gholizadeh','Torabi','Hosseini','Rezaei']},
au:{c:'AUS',f:['Harry','Mathew','Aaron','Ajdin','Jackson','Riley','Craig','Awer','Mitchell','Connor','Cameron','Kye','Jordan','Keanu','Nathaniel','Marco','Alessandro','Garang'],
 l:['Kewell','Ryan','Mooy','Hrustic','Irvine','McGree','Goodwin','Mabil','Duke','Metcalfe','Devlin','Rowles','Bos','Baccus','Atkinson','Tilio','Circati','Kuol']},
cn:{c:'CHN',f:['Wu','Zhang','Wei','Hao','Jun','Lin','Yang','Chen','Tao','Feng','Kai','Peng','Long','Bin','Cheng','Xin','Rui','Yu'],
 l:['Lei','Yuning','Shixin','Junmin','Guoxin','Hanchao','Xiaoting','Zhizhao','Lipeng','Xiaotian','Jinxiang','Yaopeng','Zhenpeng','Xuepeng','Guanyi','Boxuan','Tianyi','Hengyi']},
ma:{c:'MAR',f:['Youssef','Mehdi','Amine','Anass','Ayoub','Bilal','Hamza','Ilias','Ismail','Karim','Nabil','Omar','Rachid','Reda','Said','Soufiane','Tarik','Walid','Yassine','Zakaria'],
 l:['Alaoui','Benali','Bennani','Bouzid','Chafik','Cherkaoui','El-Amrani','El-Fassi','Hajji','Idrissi','Kabbaj','Lahlou','Mansouri','Naciri','Ouali','Raji','Sabri','Tahiri','Zerouali','Berrada']}
};
const NATKEYS=Object.keys(NATS);
const AFR=['ng','sn','gh','cm','ci','ml','cd'];
const NAF=['eg','ma','dz','tn'];
/* agent nationality → home country (league network) */
const NAT2CTRY={tr:'TR',en:'EN',es:'ES',de:'DE',it:'IT',fr:'FR',nl:'NL',pt:'PT',br:'BR',ar:'AR',
 us:'US',mx:'MX',sa:'SA',jp:'JP',ng:'WAF',sn:'WAF',gh:'WAF',cm:'WAF',eg:'NAF',ma:'NAF',
 be:'NL',hr:'IT',rs:'IT',pl:'DE',cz:'DE',gr:'IT',no:'EN',se:'EN',dk:'DE',ch:'DE',at:'DE',ua:'DE',ro:'IT',sct:'EN',ie:'EN',ru:'DE',co:'BR',uy:'AR',cl:'AR',pe:'BR',ec:'BR',py:'AR',ve:'BR',ci:'WAF',dz:'NAF',tn:'NAF',ml:'WAF',cd:'WAF',kr:'JP',ir:'SA',au:'EN',cn:'JP'};
const NATNAME={
 tr:{tr:'Türkiye',en:'Türkiye'},en:{tr:'İngiltere',en:'England'},es:{tr:'İspanya',en:'Spain'},
 de:{tr:'Almanya',en:'Germany'},it:{tr:'İtalya',en:'Italy'},fr:{tr:'Fransa',en:'France'},
 br:{tr:'Brezilya',en:'Brazil'},ar:{tr:'Arjantin',en:'Argentina'},nl:{tr:'Hollanda',en:'Netherlands'},
 pt:{tr:'Portekiz',en:'Portugal'},us:{tr:'ABD',en:'USA'},mx:{tr:'Meksika',en:'Mexico'},
 sa:{tr:'S. Arabistan',en:'Saudi Arabia'},jp:{tr:'Japonya',en:'Japan'},
 ng:{tr:'Nijerya',en:'Nigeria'},sn:{tr:'Senegal',en:'Senegal'},gh:{tr:'Gana',en:'Ghana'},
 cm:{tr:'Kamerun',en:'Cameroon'},eg:{tr:'Mısır',en:'Egypt'},ma:{tr:'Fas',en:'Morocco'},
 be:{tr:'Belçika',en:'Belgium'},
 hr:{tr:'Hırvatistan',en:'Croatia'},
 rs:{tr:'Sırbistan',en:'Serbia'},
 pl:{tr:'Polonya',en:'Poland'},
 cz:{tr:'Çekya',en:'Czechia'},
 gr:{tr:'Yunanistan',en:'Greece'},
 no:{tr:'Norveç',en:'Norway'},
 se:{tr:'İsveç',en:'Sweden'},
 dk:{tr:'Danimarka',en:'Denmark'},
 ch:{tr:'İsviçre',en:'Switzerland'},
 at:{tr:'Avusturya',en:'Austria'},
 ua:{tr:'Ukrayna',en:'Ukraine'},
 ro:{tr:'Romanya',en:'Romania'},
 sct:{tr:'İskoçya',en:'Scotland'},
 ie:{tr:'İrlanda',en:'Ireland'},
 ru:{tr:'Rusya',en:'Russia'},
 co:{tr:'Kolombiya',en:'Colombia'},
 uy:{tr:'Uruguay',en:'Uruguay'},
 cl:{tr:'Şili',en:'Chile'},
 pe:{tr:'Peru',en:'Peru'},
 ec:{tr:'Ekvador',en:'Ecuador'},
 py:{tr:'Paraguay',en:'Paraguay'},
 ve:{tr:'Venezuela',en:'Venezuela'},
 ci:{tr:'Fildişi Sahili',en:'Ivory Coast'},
 dz:{tr:'Cezayir',en:'Algeria'},
 tn:{tr:'Tunus',en:'Tunisia'},
 ml:{tr:'Mali',en:'Mali'},
 cd:{tr:'Kongo DC',en:'DR Congo'},
 kr:{tr:'G. Kore',en:'South Korea'},
 ir:{tr:'İran',en:'Iran'},
 au:{tr:'Avustralya',en:'Australia'},
 cn:{tr:'Çin',en:'China'}};
/* ================= LEAGUES / TEAMS ================= */
const CONTS=[
 ['eu', {tr:'Avrupa',en:'Europe'}],
 ['sam',{tr:'G. Amerika',en:'S. America'}],
 ['nam',{tr:'K. Amerika',en:'N. America'}],
 ['as', {tr:'Asya',en:'Asia'}],
 ['af', {tr:'Afrika',en:'Africa'}],
 ['cup',{tr:'Kupalar',en:'Cups'}]];
const CUPS=[
 {c:'EC1', n:{tr:'Kıta Kupası',en:'Continental Cup'}},
 {c:'EC2', n:{tr:'Birlik Kupası',en:'Union Cup'}},
 {c:'EC3', n:{tr:'Bölge Kupası',en:'Regional Cup'}}];
const CUPWKS=[8,14,24,32]; // R16, QF, SF, Final
const TIERS=[['TR1','TR2'],['EN1','EN2'],['ES1','ES2'],['DE1','DE2'],['IT1','IT2'],['FR1','FR2']];
const CTRYS={
 TR:{tr:'Türkiye',en:'Türkiye'},EN:{tr:'İngiltere',en:'England'},ES:{tr:'İspanya',en:'Spain'},
 DE:{tr:'Almanya',en:'Germany'},IT:{tr:'İtalya',en:'Italy'},FR:{tr:'Fransa',en:'France'},
 NL:{tr:'Hollanda',en:'Netherlands'},PT:{tr:'Portekiz',en:'Portugal'},
 BR:{tr:'Brezilya',en:'Brazil'},AR:{tr:'Arjantin',en:'Argentina'},
 US:{tr:'ABD',en:'USA'},MX:{tr:'Meksika',en:'Mexico'},
 SA:{tr:'S. Arabistan',en:'Saudi Arabia'},JP:{tr:'Japonya',en:'Japan'},
 NAF:{tr:'Kuzey Afrika',en:'North Africa'},WAF:{tr:'Batı Afrika',en:'West Africa'}};
const LEAGUES=[
 {c:'TR1',nat:'tr', con:'eu', ctry:'TR',tier:1},
 {c:'EN1',nat:'en', con:'eu', ctry:'EN',tier:1},
 {c:'ES1',nat:'es', con:'eu', ctry:'ES',tier:1},
 {c:'DE1',nat:'de', con:'eu', ctry:'DE',tier:1},
 {c:'IT1',nat:'it', con:'eu', ctry:'IT',tier:1},
 {c:'FR1',nat:'fr', con:'eu', ctry:'FR',tier:1},
 {c:'NL1',nat:'nl', con:'eu', ctry:'NL',tier:1},
 {c:'PT1',nat:'pt', con:'eu', ctry:'PT',tier:1},
 {c:'TR2',nat:'tr', con:'eu', ctry:'TR',tier:2},
 {c:'BR1',nat:'br', con:'sam',ctry:'BR',tier:1},
 {c:'AR1',nat:'ar', con:'sam',ctry:'AR',tier:1, grp:2, gl:[['Kuzey Bölgesi','Northern Zone'],['Güney Bölgesi','Southern Zone']]},
 {c:'US1',nat:'us', con:'nam',ctry:'US',tier:1, grp:2, gl:[['Doğu','Eastern'],['Batı','Western']]},
 {c:'MX1',nat:'mx', con:'nam',ctry:'MX',tier:1},
 {c:'SA1',nat:'sa', con:'as', ctry:'SA',tier:1},
 {c:'JP1',nat:'jp', con:'as', ctry:'JP',tier:1},
 {c:'NA1',nat:'afN',con:'af', ctry:'NAF',tier:1},
 {c:'WA1',nat:'af', con:'af', ctry:'WAF',tier:1},
 {c:'EN2',nat:'en', con:'eu', ctry:'EN',tier:2},
 {c:'ES2',nat:'es', con:'eu', ctry:'ES',tier:2},
 {c:'DE2',nat:'de', con:'eu', ctry:'DE',tier:2},
 {c:'IT2',nat:'it', con:'eu', ctry:'IT',tier:2},
 {c:'FR2',nat:'fr', con:'eu', ctry:'FR',tier:2}];
const TEAMS=[
/* TR1 */
[['İstanbul Sentinels','İSS','#FDB912','#A90432',77],['İstanbul Corsairs','İSC','#FFED00','#163962',77],
 ['İstanbul Spires','İSP','#e8e8e8','#141414',75],['Trabzon Vanguard','TRV','#841434','#41B6E6',73],
 ['İstanbul Compass','İCO','#FF6A13','#14295C',72],['Bursa Harvest','BUH','#0D954A','#e8e8e8',67],
 ['Ankara Orchards','ANO','#FFD200','#16265C',66],['Konya Vintners','KOV','#0A8F42','#f0f0f0',66],
 ['Antalya Pines','ANP','#E30613','#f0f0f0',65],['Sivas Willows','SİW','#D71920','#e8e8e8',65],
 ['Kayseri Herons','KAH','#E30613','#FFD500',64],['Rize Kestrels','RİK','#0072BC','#00953B',64],
 ['Alanya Stags','ALS','#F97F28','#0C8242',63],['Samsun Otters','SAO','#D40000','#f0f0f0',62],
 ['Gaziantep Clippers','GAC','#DC2626','#141414',64],['İstanbul Lagoons','İSL','#0057B8','#f0f0f0',63],
 ['İstanbul Meteors','İSM','#653D84','#FCD405',63],['Hatay Rainfall','HAR','#7A1024','#f0f0f0',62]],
/* EN1 */
[['Manchester Forges','MAF','#6CABDD','#1C2C5B',85],['London Compass','LOC','#EF0107','#f0f0f0',84],
 ['Merseyside Summit','MES','#C8102E','#F6EB61',84],['Manchester Ironworks','MAI','#DA291C','#FBE122',82],
 ['London Meridian','LOM','#034694','#f0f0f0',81],['London Comets','LCO','#f0f0f0','#132257',80],
 ['Newcastle Colliers','NEC','#241F20','#f0f0f0',79],['Birmingham Refiners','BİR','#95BFE5','#670E36',78],
 ['London Meteors','LME','#7A263A','#1BB1E7',75],['Brighton Harbour','BRH','#0057B8','#f0f0f0',75],
 ['Merseyside Basalt','MEB','#003399','#f0f0f0',74],['Wolverhampton Amphora','WOA','#FDB913','#231F20',73],
 ['London Tanners','LOT','#f0f0f0','#000000',72],['Leeds Aqueduct','LEA','#f0f0f0','#1D428A',71],
 ['London Kestrels','LOK','#DC2626','#f0f0f0',75],['Bournemouth Basalt','BOB','#DC2626','#141414',75],
 ['London Highlands','LOH','#1B458F','#DC2626',74],['Nottingham Lagoons','NOL','#DC2626','#f0f0f0',74],
 ['Burnley Terraces','BUT','#6C1D45','#8AC3EE',71],['Sheffield Granaries','SHG','#DC2626','#f0f0f0',71]],
/* ES1 */
[['Madrid Pioneers','MAP','#f0f0f0','#FEBE10',86],['Barcelona Vaults','BAV','#A50044','#004D98',85],
 ['Madrid Citadels','MAC','#CB3524','#f0f0f0',82],['Sevilla Compass','SEC','#f0f0f0','#D8091F',77],
 ['San Sebastián Summit','SAS','#0067B1','#f0f0f0',77],['Sevilla Ironworks','SEI','#00954C','#f0f0f0',76],
 ['Villarreal Sentinels','VİS','#FFE667','#005187',76],['Bilbao Citadels','BİC','#EE2523','#f0f0f0',76],
 ['Valencia Millers','VAM','#f0f0f0','#F18E00',74],['Girona Weavers','GİW','#CD2534','#f0f0f0',72],
 ['Vigo Masons','VİM','#8AC3EE','#f0f0f0',72],['Pamplona Coopers','PAC','#D91A21','#0A346F',71],
 ['Getafe Tanners','GET','#005999','#f0f0f0',70],['Mallorca Harvest','MAH','#E20613','#141414',70],
 ['Madrid Frost','MAF','#f0f0f0','#DC2626',72],['Vitoria Vintners','VİV','#0057B8','#f0f0f0',71],
 ['Barcelona Otters','BAO','#0057B8','#f0f0f0',71],['Las Palmas Willows','LAW','#FCD405','#0057B8',70],
 ['Valencia Nomads','VAN','#0A346F','#DC2626',69],['Elche Kestrels','ELK','#0A8F42','#f0f0f0',69]],
/* DE1 */
[['Munich Anchors','MUA','#DC052D','#f0f0f0',85],['Leverkusen Frigates','LEF','#E32221','#141414',81],
 ['Dortmund Pioneers','DOP','#FDE100','#141414',81],['Leipzig Vaults','LEV','#DD0741','#f0f0f0',80],
 ['Frankfurt Forges','FRF','#E1000F','#141414',76],['Stuttgart Rainfall','STR','#f0f0f0','#E32219',75],
 ['Freiburg Highlands','FRH','#E2001A','#141414',74],['Wolfsburg Coves','WOC','#65B32E','#f0f0f0',73],
 ['Gladbach Cliffs','GLC','#f0f0f0','#141414',72],['Hoffenheim Quarry','HOQ','#1961B5','#f0f0f0',72],
 ['Mainz Kilns','MAK','#C3141E','#f0f0f0',70],['Bremen Bellows','BRB','#1D9053','#f0f0f0',70],
 ['Köln Colliers','KÖC','#ED1C24','#f0f0f0',68],['Augsburg Refiners','AUR','#BA3733','#46714D',68],
 ['Berlin Saltworks','BES','#DC2626','#FCD405',70],['Hamburg Harbour','HAH','#5C3A2E','#f0f0f0',69],
 ['Heidenheim Looms','HEL','#DC2626','#0057B8',68],['Bochum Amphora','BOA','#0057B8','#f0f0f0',67]],
/* IT1 */
[['Milano Northwind','MİN','#0068A8','#141414',84],['Torino Comets','TOC','#f0f0f0','#141414',82],
 ['Milano Vaults','MİV','#FB090B','#141414',82],['Napoli Beacons','NAB','#12A0D7','#f0f0f0',82],
 ['Roma Anchors','ROA','#8E1F2F','#F0BC42',79],['Bergamo Frigates','BEF','#1E71B8','#141414',79],
 ['Roma Meteors','ROM','#87D8F7','#f0f0f0',78],['Firenze Granaries','FİG','#482E92','#f0f0f0',76],
 ['Bologna Wharf','BOW','#1A2F48','#D4172B',74],['Torino Foundry','TOF','#8B1B24','#f0f0f0',73],
 ['Sassuolo Lanterns','SAL','#00A752','#141414',70],['Udine Meteors','UDM','#f0f0f0','#141414',70],
 ['Genova Ospreys','GEO','#0071BC','#f0f0f0',68],['Genova Masons','GEM','#C8102E','#00205B',68],
 ['Monza Foundry','MOF','#DC2626','#f0f0f0',72],['Parma Wardens','PAW','#FCD405','#0057B8',72],
 ['Cagliari Millers','CAM','#8B1B24','#0A346F',71],['Verona Weavers','VEW','#FCD405','#0A346F',70],
 ['Lecce Masons','LEM','#FCD405','#DC2626',70],['Empoli Coopers','EMC','#0057B8','#f0f0f0',69]],
/* FR1 */
[['Paris Ramparts','PAR','#004170','#DA291C',85],['Monaco Lighthouse','MOL','#E63031','#f0f0f0',78],
 ['Marseille Northwind','MAN','#2FAEE0','#f0f0f0',78],['Lille Comets','LİC','#E01E13','#120E0D',76],
 ['Lyon Spires','LYS','#f0f0f0','#DA001A',75],['Rennes Willows','REW','#E13327','#141414',74],
 ['Nice Herons','NİH','#ED1C24','#141414',74],['Lens Kestrels','LEK','#FFD700','#EC1C24',73],
 ['Reims Stags','RES','#EE2223','#f0f0f0',69],['Toulouse Otters','TOO','#653D84','#f0f0f0',68],
 ['Strasbourg Clippers','STC','#009FE3','#f0f0f0',68],['Montpellier Nomads','MON','#FF6F00','#003087',67],
 ['Nantes Frost','NAF','#FCD405','#008550',66],['Bordeaux Rainfall','BOR','#001A57','#f0f0f0',65],
 ['Brest Highlands','BRH','#DC2626','#f0f0f0',68],['Auxerre Coves','AUC','#f0f0f0','#0057B8',67],
 ['Angers Cliffs','ANC','#141414','#f0f0f0',66],['Le Havre Quarry','LEQ','#8AC3EE','#0A346F',65]],
/* NL1 */
[['Amsterdam Ironworks','AMI','#f0f0f0','#D2122E',74],['Eindhoven Meridian','EİM','#ED1C24','#f0f0f0',74],
 ['Rotterdam Corsairs','ROC','#E62E2D','#141414',72],['Alkmaar Heralds','ALH','#DD1E3E','#f0f0f0',68],
 ['Enschede Ramparts','ENR','#ED1C24','#f0f0f0',66],['Utrecht Harbour','UTH','#f0f0f0','#ED1C24',63],
 ['Arnhem Looms','ARL','#FCD405','#141414',61],['Heerenveen Amphora','HEA','#0057B8','#f0f0f0',60],
 ['Groningen Cisterns','GRC','#0A8F42','#f0f0f0',60],['Nijmegen Aqueduct','NİA','#ED1C24','#141414',59],
 ['Zwolle Pastures','ZWP','#2A5CAA','#f0f0f0',58],['Almelo Basalt','ALB','#141414','#f0f0f0',57],
 ['Leeuwarden Bridges','LEB','#FCD405','#2A5CAA',56],['Volendam Lagoons','VOL','#F26522','#141414',55],
 ['Rotterdam Meteors','ROM','#DC2626','#f0f0f0',58],['Deventer Granaries','DEG','#FCD405','#DC2626',57],
 ['Sittard Wharf','SİW','#FCD405','#0A8F42',56],['Almere Arches','ALA','#141414','#DC2626',55]],
/* PT1 */
[['Lisboa Sentinels','LİS','#ED1C24','#f0f0f0',78],['Porto Citadels','POC','#0057B8','#f0f0f0',78],
 ['Lisboa Heralds','LİH','#0A8F42','#f0f0f0',77],['Braga Vanguard','BRV','#DC2626','#f0f0f0',70],
 ['Guimarães Ironworks','GUI','#f0f0f0','#141414',66],['Porto Tanners','POT','#141414','#f0f0f0',62],
 ['Famalicão Millers','FAM','#2A5CAA','#f0f0f0',61],['Estoril Weavers','ESW','#FCD405','#2A5CAA',60],
 ['Vila do Conde Masons','VİM','#0A8F42','#f0f0f0',60],['Arouca Coopers','ARC','#FCD405','#141414',59],
 ['Barcelos Tanners','BAT','#DC2626','#f0f0f0',58],['Chaves Harvest','CHH','#2A5CAA','#DC2626',58],
 ['Portimão Orchards','POO','#141414','#FCD405',57],['Moreira Vintners','MOV','#0A8F42','#FCD405',56],
 ['Açores Pines','AÇP','#DC2626','#f0f0f0',58],['Madeira Willows','MAW','#141414','#f0f0f0',57],
 ['Lisboa Cliffs','LİC','#141414','#FCD405',56],['Faro Kestrels','FAK','#f0f0f0','#141414',55]],
/* TR2 */
[['Sakarya Forges','SAF','#0C8242','#141414',58],['Kocaeli Compass','KOC','#0A6B4F','#FCD405',57],
 ['Adana Summit','ADS','#0072BC','#F26522',57],['Eskişehir Dominion','ESD','#DC2626','#141414',56],
 ['İzmir Sentinels','İZS','#141414','#f0f0f0',56],['İzmir Corsairs','İZC','#FCD405','#DC2626',56],
 ['Manisa Highlands','MAH','#141414','#DC2626',55],['Denizli Coves','DEC','#0A8F42','#141414',54],
 ['Bandırma Cliffs','BAC','#DC2626','#f0f0f0',54],['Erzurum Quarry','ERQ','#2A5CAA','#f0f0f0',53],
 ['Giresun Kilns','GİK','#0A8F42','#f0f0f0',53],['Bolu Bellows','BOB','#DC2626','#f0f0f0',52],
 ['Iğdır Colliers','IĞC','#0072BC','#0A8F42',51],['İstanbul Refiners','İSR','#00A0C6','#141414',50],
 ['Ankara Northwind','ANN','#DC2626','#141414',56],['İstanbul Pastures','İSP','#DC2626','#f0f0f0',53],
 ['İstanbul Wharf','İSW','#DC2626','#f0f0f0',52],['Ankara Bridges','ANB','#653D84','#f0f0f0',52],
 ['Çorum Cisterns','ÇOC','#DC2626','#141414',51],['Van Aqueduct','VAA','#DC2626','#8AC3EE',50]],
/* BR1 */
[['Rio Pioneers','RİP','#DC2626','#141414',76],['São Paulo Vaults','SOV','#0A8F42','#f0f0f0',76],
 ['São Paulo Citadels','SOC','#f0f0f0','#DC2626',73],['São Paulo Heralds','SOH','#141414','#f0f0f0',73],
 ['Minas Summit','MİS','#141414','#f0f0f0',72],['Alegre Dominion','ALD','#0072BC','#141414',71],
 ['Alegre Meridian','ALM','#DC2626','#f0f0f0',71],['Rio Foundry','RİF','#7A1F3D','#0A8F42',70],
 ['Santos Lanterns','SAL','#f0f0f0','#141414',69],['Rio Harvest','RİH','#141414','#f0f0f0',68],
 ['Minas Weavers','MİW','#2A5CAA','#f0f0f0',67],['Rio Stags','RİS','#141414','#DC2626',66],
 ['Salvador Foundry','SAF','#0057B8','#DC2626',64],['Fortaleza Wardens','FOW','#DC2626','#2A5CAA',63],
 ['Bragança Millers','BRM','#f0f0f0','#DC2626',66],['Recife Weavers','REW','#DC2626','#141414',64],
 ['Curitiba Masons','CUM','#0A8F42','#f0f0f0',64],['Caxias Coopers','CAC','#0A8F42','#DC2626',63],
 ['Salvador Willows','SAW','#DC2626','#141414',63],['Fortaleza Herons','FOH','#141414','#f0f0f0',62]],
/* AR1 */
[['B. Aires Anchors','BAA','#f0f0f0','#DC2626',74],['B. Aires Summit','BAS','#14295C','#FCD405',74],
 ['Avellaneda Pioneers','AVP','#8AC3EE','#f0f0f0',70],['Avellaneda Sentinels','AVS','#DC2626','#f0f0f0',68],
 ['B. Aires Corsairs','BAC','#14295C','#DC2626',67],['B. Aires Spires','BSP','#f0f0f0','#2A5CAA',66],
 ['La Plata Summit','LAS','#DC2626','#f0f0f0',65],['Rosario Dominion','ROD','#DC2626','#141414',64],
 ['Rosario Coves','ROC','#14295C','#FCD405',63],['Lanús Nomads','LAN','#7A1024','#f0f0f0',62],
 ['Córdoba Frost','CRF','#2A5CAA','#f0f0f0',61],['Banfield Rainfall','BAR','#0A8F42','#f0f0f0',60],
 ['B. Aires Wharf','BAW','#f0f0f0','#DC2626',59],['Mendoza Coves','MEC','#2A5CAA','#141414',58],
 ['B. Aires Lighthouse','BAL','#DC2626','#f0f0f0',64],['Varela Quarry','VAQ','#0A8F42','#FCD405',63],
 ['Tucumán Kilns','TUK','#8AC3EE','#f0f0f0',62],['V. López Bellows','VLB','#5C3A2E','#f0f0f0',61],
 ['B. Aires Pines','BAP','#DC2626','#f0f0f0',61],['Tigre Refiners','TİR','#0057B8','#DC2626',60],
 ['Santa Fe Saltworks','SAS','#DC2626','#f0f0f0',60],['La Plata Pastures','LAP','#f0f0f0','#0A346F',60],
 ['Córdoba Basalt','CRB','#DC2626','#f0f0f0',59],['B. Aires Highlands','BAH','#141414','#f0f0f0',59],
 ['Mendoza Lagoons','MEL','#7A1024','#f0f0f0',58],['Junín Aqueduct','JUA','#0A8F42','#f0f0f0',58],
 ['Mar Plata Pastures','MAP','#FCD405','#0A8F42',57],['San Juan Basalt','SAB','#0A8F42','#141414',57],
 ['Córdoba Foundry','CFO','#8AC3EE','#141414',60],['Santiago Lagoons','SAL','#141414','#8AC3EE',58]],
/* US1 */
[['Miami Sentinels','MİS','#F7B5CD','#141414',68],['Los Angeles Citadels','LOC','#141414','#C39E6D',67],
 ['Los Angeles Heralds','LOH','#f0f0f0','#14295C',66],['Atlanta Vanguard','ATV','#7A1024','#141414',65],
 ['Seattle Ironworks','SEI','#0A8F42','#2A5CAA',64],['Columbus Meridian','COM','#FCD405','#141414',63],
 ['Cincinnati Corsairs','CİC','#F26522','#2A5CAA',62],['Austin Voyagers','AUV','#65B32E','#141414',61],
 ['Dallas Foundry','DAF','#DC2626','#2A5CAA',60],['Chicago Wardens','CHW','#DC2626','#14295C',59],
 ['Orlando Millers','ORM','#653D84','#FCD405',59],['Portland Weavers','POW','#0A6B4F','#FCD405',58],
 ['Nashville Masons','NAM','#FCD405','#14295C',57],['Denver Coopers','DEC','#7A1024','#8AC3EE',56],
 ['San Diego Anchors','SAA','#00A0C6','#F7B5CD',65],['St. Louis Frigates','STF','#DC2626','#0057B8',63],
 ['Charlotte Pioneers','CHP','#00A0C6','#141414',62],['San Jose Vintners','SAV','#0057B8','#141414',61],
 ['Houston Pines','HOP','#F26522','#141414',61],['Kansas City Willows','KAW','#8AC3EE','#0A346F',61],
 ['Minnesota Herons','MİH','#8AC3EE','#141414',60],['Salt Lake Kestrels','SAK','#7A1024','#FCD405',60],
 ['Vancouver Stags','VAS','#f0f0f0','#0A346F',60],['Toronto Otters','TOO','#DC2626','#f0f0f0',59],
 ['Montréal Clippers','MOC','#0057B8','#141414',59],['New York Nomads','NEN','#DC2626','#f0f0f0',59],
 ['New York Quarry','NEQ','#8AC3EE','#F26522',58],['Philly Rainfall','PHR','#0A346F','#FCD405',58],
 ['Washington Highlands','WAH','#141414','#DC2626',57],['New England Coves','NEC','#0A346F','#DC2626',57]],
/* MX1 */
[['México Ramparts','MXR','#FCD405','#14295C',70],['Monterrey Lighthouse','MOL','#14295C','#f0f0f0',69],
 ['Monterrey Frigates','MOF','#FCD405','#2A5CAA',69],['Guadalajara Comets','GUC','#DC2626','#f0f0f0',67],
 ['México Vaults','MXV','#0057B8','#f0f0f0',66],['México Lagoons','MXL','#14295C','#C39E6D',65],
 ['Toluca Saltworks','TOS','#DC2626','#f0f0f0',64],['León Harbour','LEH','#0A8F42','#FCD405',63],
 ['Pachuca Looms','PAL','#14295C','#f0f0f0',62],['Torreón Amphora','TOA','#0A8F42','#f0f0f0',61],
 ['Guadalajara Lagoons','GUL','#DC2626','#141414',60],['Puebla Aqueduct','PUA','#f0f0f0','#2A5CAA',59],
 ['Tijuana Pastures','TİP','#DC2626','#141414',58],['Querétaro Basalt','QUB','#141414','#2A5CAA',57],
 ['Juárez Bridges','JUB','#0A8F42','#DC2626',59],['Aguascalientes Lagoons','AGL','#DC2626','#f0f0f0',59],
 ['San Luis Terraces','SAT','#DC2626','#0A346F',58],['Mazatlán Granaries','MAG','#653D84','#FCD405',57]],
/* SA1 */
[['Riyadh Ironworks','RİI','#0057B8','#f0f0f0',76],['Riyadh Northwind','RİN','#FCD405','#2A5CAA',75],
 ['Jeddah Corsairs','JEC','#FCD405','#141414',73],['Jeddah Spires','JES','#0A8F42','#f0f0f0',71],
 ['Riyadh Orchards','RİO','#f0f0f0','#141414',65],['Buraydah Voyagers','BUV','#FCD405','#0057B8',61],
 ['Hofuf Foundry','HOF','#0A8F42','#f0f0f0',60],['Khamis Wardens','KHW','#DC2626','#2A5CAA',59],
 ['Buraydah Harvest','BUH','#0057B8','#FCD405',58],['Mecca Weavers','MEW','#DC2626','#f0f0f0',58],
 ['Harmah Masons','HAM','#2A5CAA','#FCD405',57],['Saihat Coopers','SAC','#0A8F42','#141414',56],
 ['Abha Tanners','ABT','#8AC3EE','#f0f0f0',55],['Rass Harvest','RAH','#DC2626','#FCD405',54],
 ['Khobar Forges','KHF','#FCD405','#141414',66],['Riyadh Kilns','RİK','#0057B8','#FCD405',57],
 ['Sakaka Pines','SAP','#0A8F42','#f0f0f0',56],['Najran Willows','NAW','#F26522','#141414',55]],
/* JP1 */
[['Kawasaki Sentinels','KAS','#8AC3EE','#141414',66],['Yokohama Citadels','YOC','#0057B8','#DC2626',65],
 ['Saitama Bastions','SAB','#DC2626','#141414',64],['Kashima Vanguard','KAV','#7A1024','#141414',64],
 ['Tokyo Ironworks','TOI','#0057B8','#DC2626',62],['Osaka Meridian','OSM','#0057B8','#141414',62],
 ['Kobe Frost','KOF','#7A1024','#f0f0f0',61],['Nagoya Rainfall','NAR','#DC2626','#FCD405',60],
 ['Hiroshima Highlands','HİH','#653D84','#f0f0f0',59],['Fukuoka Coves','FUC','#14295C','#f0f0f0',58],
 ['Sapporo Cliffs','SAC','#DC2626','#141414',57],['Kyoto Quarry','KYQ','#653D84','#FCD405',56],
 ['Hiratsuka Kilns','HİK','#65B32E','#8AC3EE',55],['Sendai Bellows','SEB','#FCD405','#14295C',55],
 ['Machida Anchors','MAA','#0A346F','#FCD405',64],['Kashiwa Frigates','KAF','#FCD405','#141414',62],
 ['Osaka Aqueduct','OSA','#F7B5CD','#653D84',61],['Shizuoka Harbour','SHH','#F26522','#141414',60],
 ['Niigata Looms','NİL','#F26522','#0057B8',58],['Okayama Amphora','OKA','#8B1B24','#FCD405',57]],
/* NA1 */
[['Cairo Summit','CAS','#DC2626','#f0f0f0',58],['Cairo Ironworks','CAI','#f0f0f0','#DC2626',57],
 ['Tunis Sentinels','TUS','#FCD405','#DC2626',56],['Casablanca Citadels','CAC','#DC2626','#141414',55],
 ['Casablanca Heralds','CAH','#0A8F42','#f0f0f0',55],['Sfax Lagoons','SFL','#f0f0f0','#141414',52],
 ['Sétif Terraces','STT','#141414','#f0f0f0',51],['Tizi Ouzou Granaries','TİG','#FCD405','#0A8F42',50],
 ['Algiers Wharf','ALW','#DC2626','#f0f0f0',49],['Ismailia Arches','ISA','#FCD405','#2A5CAA',48],
 ['Tetouan Lanterns','TEL','#653D84','#f0f0f0',47],['Bizerte Meteors','BİM','#141414','#FCD405',46],
 ['Oran Ospreys','ORO','#DC2626','#f0f0f0',45],['Tripoli Voyagers','TRV','#0A8F42','#DC2626',45]],
/* WA1 */
[['Lagos Spires','LAS','#0A8F42','#f0f0f0',50],['Dakar Beacons','DAB','#0C8242','#FCD405',49],
 ['Accra Anchors','ACA','#DC2626','#FCD405',48],['Abidjan Frigates','ABF','#F26522','#0A8F42',47],
 ['Kumasi Masons','KUM','#FCD405','#141414',46],['Conakry Coopers','COC','#DC2626','#FCD405',46],
 ['Nairobi Tanners','NAT','#DC2626','#0A8F42',45],['Yaoundé Harvest','YAH','#0A8F42','#DC2626',45],
 ['Bamako Orchards','BAO','#FCD405','#0A8F42',44],['Lomé Vintners','LOV','#0A8F42','#FCD405',44],
 ['Luanda Pines','LUP','#DC2626','#141414',43],['Cotonou Willows','COW','#0A8F42','#DC2626',43],
 ['Freetown Herons','FRH','#0072BC','#0A8F42',42],['Kinshasa Kestrels','KİK','#2A5CAA','#FCD405',42]],
/* EN2 */
[['Norwich Ironworks','NOI','#DC2626','#f0f0f0',67],['Watford Meridian','WAM','#0057B8','#f0f0f0',67],
 ['Middlesbrough Corsairs','MİC','#0A8F42','#f0f0f0',66],['Coventry Heralds','COH','#FCD405','#141414',66],
 ['Preston Ramparts','PRR','#141414','#f0f0f0',65],['Hull Lighthouse','HUL','#F26522','#141414',65],
 ['Stoke Northwind','STN','#2A5CAA','#FCD405',64],['Swansea Comets','SWC','#7A1024','#f0f0f0',64],
 ['Cardiff Cliffs','CAC','#653D84','#f0f0f0',63],['Bristol Quarry','BRQ','#00A0C6','#141414',63],
 ['London Kilns','LOK','#8B1B24','#FCD405',62],['London Looms','LOL','#1D9053','#141414',62],
 ['Blackburn Colliers','BLC','#DC2626','#f0f0f0',61],['Birmingham Pastures','BİP','#0057B8','#f0f0f0',61],
 ['Derby Saltworks','DES','#0A8F42','#f0f0f0',60],['Portsmouth Harbour','POH','#FCD405','#141414',60],
 ['Luton Looms','LUL','#141414','#f0f0f0',59],['Ipswich Amphora','IPA','#F26522','#141414',59],
 ['Sandwell Cisterns','SAC','#2A5CAA','#FCD405',58],['Plymouth Aqueduct','PLA','#7A1024','#f0f0f0',58],
 ['Oxford Pastures','OXP','#653D84','#f0f0f0',57],['Wrexham Basalt','WRB','#00A0C6','#141414',57],
 ['London Foundry','LOF','#8B1B24','#FCD405',56],['Reading Lagoons','REL','#1D9053','#141414',56]],
/* ES2 */
[['Zaragoza Corsairs','ZAC','#DC2626','#f0f0f0',64],['A Coruña Heralds','ACH','#0057B8','#f0f0f0',64],
 ['Gijón Ramparts','GİR','#0A8F42','#f0f0f0',63],['Santander Lighthouse','SAL','#FCD405','#141414',63],
 ['Oviedo Northwind','OVN','#141414','#f0f0f0',62],['Cádiz Comets','CDC','#F26522','#141414',62],
 ['Granada Ospreys','GRO','#2A5CAA','#FCD405',61],['Almería Voyagers','ALV','#7A1024','#f0f0f0',61],
 ['Tenerife Foundry','TEF','#653D84','#f0f0f0',60],['Burgos Wardens','BUW','#00A0C6','#141414',60],
 ['Eibar Millers','EİM','#8B1B24','#FCD405',59],['Huesca Weavers','HUW','#1D9053','#141414',59],
 ['Albacete Masons','ALM','#DC2626','#f0f0f0',58],['Miranda Coopers','MİC','#0057B8','#f0f0f0',58],
 ['Cartagena Tanners','CAT','#0A8F42','#f0f0f0',57],['Ferrol Harvest','FEH','#FCD405','#141414',57],
 ['Leganés Orchards','LEO','#141414','#f0f0f0',56],['Valladolid Vintners','VAV','#F26522','#141414',56],
 ['Castellón Pines','CAP','#2A5CAA','#FCD405',55],['Elda Willows','ELW','#7A1024','#f0f0f0',55],
 ['Andorra Herons','ANH','#653D84','#f0f0f0',54],['Córdoba Kestrels','CRK','#00A0C6','#141414',54]],
/* DE2 */
[['Hamburg Corsairs','HAC','#DC2626','#f0f0f0',65],['Berlin Heralds','BEH','#0057B8','#f0f0f0',64],
 ['Gelsenkirchen Ramparts','GER','#0A8F42','#f0f0f0',64],['Düsseldorf Lighthouse','DÜL','#FCD405','#141414',63],
 ['Hannover Northwind','HAN','#141414','#f0f0f0',63],['Kaiserslautern Rainfall','KAR','#F26522','#141414',62],
 ['Nürnberg Highlands','NÜH','#2A5CAA','#FCD405',61],['Karlsruhe Coves','KAC','#7A1024','#f0f0f0',61],
 ['Paderborn Cliffs','PAC','#653D84','#f0f0f0',60],['Magdeburg Quarry','MAQ','#00A0C6','#141414',60],
 ['Darmstadt Kilns','DAK','#8B1B24','#FCD405',59],['Fürth Bellows','FÜB','#1D9053','#141414',59],
 ['Braunschweig Colliers','BRC','#DC2626','#f0f0f0',58],['Ulm Refiners','ULR','#0057B8','#f0f0f0',57],
 ['Regensburg Saltworks','RES','#0A8F42','#f0f0f0',57],['Münster Harbour','MÜH','#FCD405','#141414',56],
 ['Elversberg Looms','ELL','#141414','#f0f0f0',56],['Dresden Amphora','DRA','#F26522','#141414',55]],
/* IT2 */
[['Palermo Bastions','PAB','#DC2626','#f0f0f0',63],['Bari Vanguard','BAV','#0057B8','#f0f0f0',62],
 ['Brescia Ironworks','BRI','#0A8F42','#f0f0f0',62],['La Spezia Meridian','LAM','#FCD405','#141414',61],
 ['Cremona Corsairs','CRC','#141414','#f0f0f0',61],['Pisa Heralds','PİH','#F26522','#141414',60],
 ['Modena Ramparts','MOR','#2A5CAA','#FCD405',60],['Reggio Granaries','REG','#7A1024','#f0f0f0',59],
 ['Catanzaro Wharf','CAW','#653D84','#f0f0f0',59],['Venezia Arches','VEA','#00A0C6','#141414',58],
 ['Frosinone Lanterns','FRL','#8B1B24','#FCD405',58],['Salerno Meteors','SAM','#1D9053','#141414',57],
 ['Cesena Ospreys','CEO','#DC2626','#f0f0f0',57],['Bolzano Voyagers','BOV','#0057B8','#f0f0f0',56],
 ['Cosenza Foundry','COF','#0A8F42','#f0f0f0',56],['Mantova Wardens','MAW','#FCD405','#141414',55],
 ['Stabia Millers','STM','#141414','#f0f0f0',55],['Carrara Weavers','CWE','#F26522','#141414',54],
 ['Terni Masons','TEM','#2A5CAA','#FCD405',54],['Perugia Coopers','PEC','#7A1024','#f0f0f0',53]],
/* FR2 */
[['Metz Sentinels','MES','#DC2626','#f0f0f0',62],['Caen Citadels','CAC','#0057B8','#f0f0f0',61],
 ['Guingamp Bastions','GUB','#0A8F42','#f0f0f0',61],['Lorient Vanguard','LOV','#FCD405','#141414',60],
 ['Grenoble Ironworks','GRI','#141414','#f0f0f0',60],['Amiens Willows','AMW','#F26522','#141414',59],
 ['Annecy Herons','ANH','#2A5CAA','#FCD405',58],['Pau Kestrels','PAK','#7A1024','#f0f0f0',58],
 ['Laval Stags','LAS','#653D84','#f0f0f0',57],['Rodez Otters','ROO','#00A0C6','#141414',57],
 ['Bastia Clippers','BAC','#8B1B24','#FCD405',56],['Ajaccio Nomads','AJN','#1D9053','#141414',56],
 ['Troyes Frost','TRF','#DC2626','#f0f0f0',55],['Dunkerque Rainfall','DUR','#0057B8','#f0f0f0',54],
 ['Clermont Highlands','CLH','#0A8F42','#f0f0f0',54],['Valenciennes Coves','VAC','#FCD405','#141414',53],
 ['Sochaux Cliffs','SOC','#141414','#f0f0f0',53],['Nancy Quarry','NAQ','#F26522','#141414',52]]];
/* Uyruk → kıta. Kurulum ekranı önce kıta, sonra ülke sorar; 52 ülkeyi tek listede
   göstermek okunmuyordu. Futbol federasyonu esas alındı: Türkiye ve Rusya Avrupa. */
const NCONTS=[
 ['eu', {tr:'Avrupa',en:'Europe'}],
 ['sam',{tr:'Güney Amerika',en:'South America'}],
 ['nam',{tr:'Kuzey Amerika',en:'North America'}],
 ['af', {tr:'Afrika',en:'Africa'}],
 ['as', {tr:'Asya',en:'Asia'}],
 ['oc', {tr:'Okyanusya',en:'Oceania'}]];
const NATCON={
 tr:'eu',en:'eu',es:'eu',de:'eu',it:'eu',fr:'eu',nl:'eu',pt:'eu',be:'eu',hr:'eu',rs:'eu',pl:'eu',
 cz:'eu',gr:'eu',no:'eu',se:'eu',dk:'eu',ch:'eu',at:'eu',ua:'eu',ro:'eu',sct:'eu',ie:'eu',ru:'eu',
 br:'sam',ar:'sam',co:'sam',uy:'sam',cl:'sam',pe:'sam',ec:'sam',py:'sam',ve:'sam',
 us:'nam',mx:'nam',
 ng:'af',sn:'af',gh:'af',cm:'af',eg:'af',ma:'af',ci:'af',dz:'af',tn:'af',ml:'af',cd:'af',
 sa:'as',jp:'as',kr:'as',ir:'as',cn:'as',
 au:'oc'};
const POS=['KL','DF','OS','FV'];
const POSL={tr:{KL:'KL',DF:'DF',OS:'OS',FV:'FV'},en:{KL:'GK',DF:'DF',OS:'MF',FV:'FW'}};
const POSFULL={tr:{KL:'Kaleci',DF:'Defans',OS:'Orta Saha',FV:'Forvet'},en:{KL:'Goalkeeper',DF:'Defender',OS:'Midfielder',FV:'Forward'}};
